/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ObligacionesRouteImport } from './routes/obligaciones'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpresasEmpresaIdRouteImport } from './routes/empresas.$empresaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ObligacionesRoute = ObligacionesRouteImport.update({
  id: '/obligaciones',
  path: '/obligaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasEmpresaIdRoute = EmpresasEmpresaIdRouteImport.update({
  id: '/empresas/$empresaId',
  path: '/empresas/$empresaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/obligaciones': typeof ObligacionesRoute
  '/empresas/$empresaId': typeof EmpresasEmpresaIdRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/obligaciones': typeof ObligacionesRoute
  '/empresas/$empresaId': typeof EmpresasEmpresaIdRoute
  '/empresas': typeof EmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/obligaciones': typeof ObligacionesRoute
  '/empresas/$empresaId': typeof EmpresasEmpresaIdRoute
  '/empresas/': typeof EmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/obligaciones'
    | '/empresas/$empresaId'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/calendario' | '/obligaciones' | '/empresas/$empresaId' | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/obligaciones'
    | '/empresas/$empresaId'
    | '/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ObligacionesRoute: typeof ObligacionesRoute
  EmpresasEmpresaIdRoute: typeof EmpresasEmpresaIdRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obligaciones': {
      id: '/obligaciones'
      path: '/obligaciones'
      fullPath: '/obligaciones'
      preLoaderRoute: typeof ObligacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$empresaId': {
      id: '/empresas/$empresaId'
      path: '/empresas/$empresaId'
      fullPath: '/empresas/$empresaId'
      preLoaderRoute: typeof EmpresasEmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ObligacionesRoute: ObligacionesRoute,
  EmpresasEmpresaIdRoute: EmpresasEmpresaIdRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
